name: Build and Release Executable

on:
  push:
    tags:
      - 'v*.*.*' # Ao criar tags (ex.: v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --name=privacy_scraper main.py

      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium

      - name: Prepare files
        shell: pwsh
        run: |
          mkdir release
          Copy-Item dist\* release\ -Recurse -Force
          
          if (Test-Path ".env") { 
            Copy-Item .env release\privacy_scraper\ -Force
          }

          $sourceChromium = "$env:USERPROFILE\AppData\Local\ms-playwright"
          $internalPath = "release\privacy_scraper\_internal\playwright-browsers"

          if (Test-Path $sourceChromium) {
            New-Item -ItemType Directory -Path $internalPath -Force
            Copy-Item "$sourceChromium\*" $internalPath -Recurse -Force
          } else {
            Write-Error "Chromium not found in expected path: $sourceChromium"
            exit 1
          }

      - name: Zip files
        run: Compress-Archive -Path release\* -DestinationPath privacy_scraper_windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: privacy_scraper_windows.zip
